### ISSUE TITLE
Improvement request: retrieve a child attribute from a parent

### ISSUE THREAD

**Issue by seb-bardon-cyb** [Ayudante/parent-element-variable#2]
Hello,

What I would like to do is to be able to retrieve the information of a child from a find parent.
I currently do this through custom JS but it's not clean and don't use Sandbox.

Let's take for example :

HTML : 
```html
<div id="map">
		<div data-country="fr">
			<p>
				<span class="name">Paris</span>
				<span class="top">Place Vendôme</span>
			<p>
		</div>
		<div data-country="fr">
			<p>
				<span class="name">Lyon</span>
				<span class="top">Place Bellecour</span>
			<p>
		</div>
		<div data-country="en">
			<p>
				<span class="name">Londres</span>
				<span class="top">Tower Bridge</span>
			<p>
		</div>
		<div data-country="de">
			<p>
				<span class="name">Berlin</span>
				<span class="top">Porte de Brandebourg</span>
			<p>
		</div>
</div>
```
Objective: Create two variables to obtain, when clicking in a map :
	- The "data-country" attribute
	- The text present in the div Class "name".

Trigger : 

> ClickElement - Css Selector - "[data-country], [data-country] *"

Variable Attribute data-country : I use your model.

Variable Text class name : Custom JS Variable :

> return {{clickElement}}.closest('[data-country]').querySelector('.name').innerText.trim(); // Or other value, title, className ...

Here I would like to use your template to be able to go through the children of the configured parent and get the text or any attribute.

Thanking you in advance for any feedback and your work
Sincerely 

Translated with www.DeepL.com

**Comment by DaisakuHataoka** [comment]
Hello, seb-bardon-cyb!
Sorry for the very late reply.

Thank you for the great usage suggestions.
Your sample JavaScript is also very clean and beautiful!

In fact, there were some situations where I wanted to use it for the same purpose.
However, due to the limitations of the sandbox, I could not easily implement it in the template, so I had to pass on it.
However, it would still be useful (especially for those who are not good with JavaScript) if it could be done, so I will look forward to considering it.

Translated with www.DeepL.com/Translator (free version)

**Comment by DaisakuHataoka** [comment]
Thank you for your patience.
However, I must make an unfortunate announcement.

I tried to find a way to make it work, but we could not do so because we were caught in a constraint.
I hope to be able to work on this project someday when the specifications are relaxed.

**Comment by seb-bardon-cyb** [comment]
Thank you for taking the time to look and for your work. Best regards
